on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo docker image build & ECR push : xxxx.dkr.ecr.ap-northeast-2.amazonaws.com/tag-test:$RELEASE_VERSION
          echo docker image build & ECR push : xxxx.dkr.ecr.ap-northeast-2.amazonaws.com/tag-test:${{ steps.vars.outputs.tag }}
